name: Only branch deploy

on:
  workflow_dispatch:
    inputs:
      website_url:
        description: "Website URL to be used in the workflow"
        default: "https://staging.propulsivetech.com"
        required: true
      user_name:
        description: "User Name to be used in the workflow"
        default: "shardul"
        required: true
      user_email:
        description: "User Email to be used in the workflow"
        default: "shardulgaikwad@gmail.com"
        required: true
      netlify_site_id:
        description: "Netlify site id"
        required: true
  push:
    branches:
      - main

jobs:
  roughBook:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.

      - name: Print GitHub Event Inputs
        run: |
          echo "GitHub Event Inputs:"
          echo "${{ toJson(github.event.inputs) }}" | yq eval 'map(.)' -

      - name: Move reports to build folder
        run: mkdir build && mv ./static-report/* ./build/

      - name: Deploy report to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./build"
          production-branch: main
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "New Release Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          github-deployment-environment: production
          github-deployment-description: "Deployment description from main.yml"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ github.event.inputs.netlify_site_id }}
        timeout-minutes: 1
